[project]
name = "rmai-verification"
version = "0.1.0"
description = "Toolbox to load, align and compare meteorological forecasts and observations in different formats."
authors = [
    {name = "Michiel Van Ginderachter",email = "michiel.vanginderachter@meteo.be"},
    {name = "Dieter Van den Bleeken"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"

dependencies = [
    "netcdf4 (>=1.7.2,<2.0.0)",
    "h5netcdf (>=1.6.1,<2.0.0)",
    "xarray (>=2024.10)",
    "Cartopy (>=0.23)",
    "zarr (>=2.16)",
    "pandas (>=2.2)",
    "xskillscore (>=0.0.24)",
    "PyYAML (>=6.0.0)",
    "matplotlib (>= 3.9.0)",
    "dask (>=2024.0)",
    "cfgrib (>=0.9.15.1,<0.10.0.0)",
    "scores (>=2.4.0,<3.0.0)",
    "jinja2 (>=3.1)",
    "markupsafe (>=2.1)"
]

[project.optional-dependencies]
cluster = ["dask-jobqueue (>=0.8)"]
scores  = ["scores (>=2.0.0)"]
dev = [
    "dask-jobqueue (>=0.8)", 
    "poetry (>=2.0)",
]
dashboard = [
    "bokeh (>=3.1.0)"
]

[tool.poetry]
packages = [{include = "rmai_verification", from = "src"}]

[tool.poetry.scripts]
rmai-verification = "rmai_verification.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
