dates:
  start: 2020-01-02 00:00:00
  end: 2020-12-25 00:00:00
  frequency: 1D

datastores:
  la-0512-00-ea-00:
    type: anemoi-inference
    path: /scratch/project_465000527/vandenbl/sg-la-comparison/inference-out/la-0512-00-ea-00/{yyyy}{mm}{dd}{HH}.nc
    mapping: cerra
    variables: ['10u_10', '10v_10', '2d_2', '2t_2', 'msl_0', 'q_500', 'skt', 'sp', 't_500', 'u_500', 'z_500']

  cerra:
    type: anemoi-datasets
    path: /scratch/project_465001235/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-rmi.zarr
    mapping: cerra
    variables: ['10u_10', '10v_10', '2d_2', '2t_2', 'msl_0', 'q_500', 'skt', 'sp', 't_500', 'u_500', 'z_500']

transformations:
  rename:
    rename_dict:
      2t: [2t_2, T2M]
      2d: [2d_2, TD2M]
      10u: [10u_10, U10M]
      10v: [10v_10, V10M]
      10s: [S10M, 10s_10]
      msl: [msl_0, MLSP]
  uv_to_speed:
    datastores:
      - la-0512-00-ea-00
      - cerra
    u: 10u
    v: 10v
    speed: 10s

verification:
  reference_datastore: cerra    
  variables : ['10s', '2d', '2t', 'msl', 'q_500', 'skt', 'sp', 't_500', 'u_500', 'z_500']
  clusters:
    temporal:
      package : scores
      metrics:
        - mse
        - bias
      avg_dims: [reference_time]

output:
  type: netcdf
  temporal:
    path: /scratch/project_465000527/vandenbl/sg-la-comparison/scores/la-0512-00-ea-00_vs_cerra_small.nc
