dates:
  start: 2020-01-02 00:00:00
  end: 2020-12-27 00:00:00
  frequency: 48h

datastores:
  lam-512-600km-rollout-fix:
    type: anemoi-inference
    path: /scratch/project_465001235/vandenbl/anemoi/experiments/inference/lam_512_600km_rollout_fix/outputs/{yyyy}{mm}{dd}{HH}.nc
    mapping: cerra

  cerra:
    type: anemoi-datasets
    path: /scratch/project_465001235/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-3h-v2-rmi.zarr
    mapping: cerra

transformations:
  rename:
    rename_dict:
      2t: [2t_2, T2M]
      2d: [2d_2 TD2M]
      10u: [10u_10, U10M]
      10v: [10v_10, V10M]
      10s: [S10M, 10s_10]
      msl: [msl_0, MLSP]
  uv_to_speed:
    u: 10u
    v: 10v
    speed: 10s
  # kelvin_to_celcius:
  #   datastores:
  #     - stretched-512
  #     - cerra
  #   fields: [2t]

verification:
  reference_datastore: cerra    
  variables : [2t, 10s, msl, z_500, q_500, t_500]
  clusters:
    temporal:
      package : xskillscore
      metrics:
        - mse
        - bias
        - rmse
      avg_dims: [reference_time]

output:
  type: netcdf
  temporal:
    path: ./results/LAM_512_600KM_ROLLOUT_FIXvCERRA.nc

# visualization:
#   temporal:
#     directory: "./"
#     prefix: "STRETCHEDvALO4vIFSHRESvCERRA"
#     x: "lead_time"    
